### ISSUE TITLE
Clear Filter/Searchbox Input

### ISSUE THREAD

**Issue by poetawd** [fabianlindfors/multi.js#30]
Hello !

Great plugin ! Looks AMAZING and really helped my users !

I want to know if there is a way to programmatically clear Filter/Searchbox input and show all the options available.

I tried everything, nothing works to show the options list back again... 

```
     var select = $("select#" + select_id);

            select.parent().find(".search-input").focus();
            select.parent().find(".search-input").val('');  //Clear the input value...
            select.parent().find(".search-input").keyup();
            select.parent().find(".search-input").change();

            select.trigger("change");
            select.trigger("click");
            select.parent().find(".search-input").trigger("click");
            select.parent().find(".search-input").trigger("change");
            select.parent().find(".search-input").trigger("keyup");
            select.parent().find(".search-input").trigger("keydown");
```

**Comment by fabianlindfors** [comment]
Hi!

The search input reacts to the `input` event to refresh. Something like `select.parent().find(".search-input").trigger("input");` should work!

**Comment by poetawd** [comment]
Still not working... Is there anything I can send you to show that it is not working correctly ? Any logs... debug... A video ? Thank you !!!

**Comment by fabianlindfors** [comment]
Yes! Please attach the full code you use to init multi.js and the code you use to clear the search field :)

**Comment by 2x2p** [comment]
Just an idea I came across as I was tweaking a bit yesterday to understand it al better and coincidentally stumbled upon this part below in multi.js because I had an other CSS part handling the input[type="text"] and was surprised the multi search bar unexpectedly became a different border-color. I solved it by taking that in to a different class so it doesn't affect the elements within multi anymore.
```
    // Add search bar
    if (settings.enable_search) {
      var search = document.createElement("input");
      search.className = "search-input";
      search.type = "text";
      search.setAttribute("placeholder", settings.search_placeholder);
```
However out of curiosity I also tried setting `search.type = "search";` for a test in multi.js

And I noticed the multi search bar got the default OS look and now had the "Clear Input" Icon as I though was asked for by poetawd, yet I see this is not programmatically. Still  I wonder if it should be actually `search.type = "search";` and then make the CSS part handle that element to again fit the sleek multi style ?

![Screen Shot 2019-05-08 at 18 16 41](https://user-images.githubusercontent.com/49434354/57390863-925f7d80-71bd-11e9-855a-007d2a2ba4ec.png)

**Comment by rapto** [comment]
This worked for me:
```
            const ev = new Event('input');
            const s = $('select');
            s.val("");
            for (const f of s.parent().find(".search-input")){  
                f.dispatchEvent(ev);
            }
```
